# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlddata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='world_areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(default=b'', max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('background', models.CharField(blank=True, max_length=255)),
                ('background_point', models.CharField(blank=True, max_length=80)),
                ('corresp_map_pos', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'World Area',
                'verbose_name_plural': 'World Areas',
            },
        ),
        migrations.AddField(
            model_name='world_rooms',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='world_rooms',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
