# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-14 16:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='career_equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(db_index=True, max_length=255)),
                ('equipment', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Career Equip Relation',
                'verbose_name_plural': 'Career Equip Relations',
            },
        ),
        migrations.CreateModel(
            name='character_careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='character_loot_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=255)),
                ('object', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(blank=True, default=0)),
                ('odds', models.FloatField(blank=True, default=0)),
                ('quest', models.CharField(blank=True, max_length=255)),
                ('condition', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Character's Loot List",
                'verbose_name_plural': "Character's Loot Lists",
            },
        ),
        migrations.CreateModel(
            name='character_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('level', models.PositiveIntegerField(blank=True, default=1)),
                ('max_exp', models.PositiveIntegerField(blank=True, default=0)),
                ('max_hp', models.PositiveIntegerField(blank=True, default=1)),
                ('max_mp', models.PositiveIntegerField(blank=True, default=1)),
                ('attack', models.IntegerField(blank=True, default=1)),
                ('defence', models.IntegerField(blank=True, default=0)),
                ('give_exp', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Character Model',
                'verbose_name_plural': 'Character Models',
            },
        ),
        migrations.CreateModel(
            name='class_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('system_data', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Class Category',
                'verbose_name_plural': 'Class Categories',
            },
        ),
        migrations.CreateModel(
            name='client_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_room_size', models.FloatField(blank=True, default=40.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('map_scale', models.FloatField(blank=True, default=75.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('show_command_box', models.BooleanField(default=False)),
                ('can_close_dialogue', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Webclient Setting',
                'verbose_name_plural': 'Webclient Settings',
            },
        ),
        migrations.CreateModel(
            name='common_characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('model', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(blank=True, default=1)),
                ('icon', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Common Character List',
                'verbose_name_plural': 'Common Character List',
            },
        ),
        migrations.CreateModel(
            name='common_objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('max_stack', models.PositiveIntegerField(blank=True, default=1)),
                ('unique', models.BooleanField(default=False)),
                ('can_remove', models.BooleanField(default=True)),
                ('can_discard', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Common Object',
                'verbose_name_plural': 'Common Objects',
            },
        ),
        migrations.CreateModel(
            name='creator_loot_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=255)),
                ('object', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(blank=True, default=0)),
                ('odds', models.FloatField(blank=True, default=0)),
                ('quest', models.CharField(blank=True, max_length=255)),
                ('condition', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Object Creator's Loot List",
                'verbose_name_plural': "Object Creator's Loot Lists",
            },
        ),
        migrations.CreateModel(
            name='default_objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(db_index=True, max_length=255)),
                ('object', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Character's Default Object",
                'verbose_name_plural': "Character's Default Objects",
            },
        ),
        migrations.CreateModel(
            name='default_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(db_index=True, max_length=255)),
                ('skill', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Character's Skill",
                'verbose_name_plural': "Character's Skills",
            },
        ),
        migrations.CreateModel(
            name='dialogue_quest_dependencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue', models.CharField(db_index=True, max_length=255)),
                ('dependency', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Dialogue Quest Dependency',
                'verbose_name_plural': 'Dialogue Quest Dependencies',
            },
        ),
        migrations.CreateModel(
            name='dialogue_relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue', models.CharField(db_index=True, max_length=255)),
                ('next_dlg', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Dialogue Relation',
                'verbose_name_plural': 'Dialogue Relations',
            },
        ),
        migrations.CreateModel(
            name='dialogue_sentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue', models.CharField(db_index=True, max_length=255)),
                ('ordinal', models.IntegerField()),
                ('speaker', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('action', models.TextField(blank=True)),
                ('provide_quest', models.CharField(blank=True, max_length=255)),
                ('complete_quest', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Dialogue Sentence',
                'verbose_name_plural': 'Dialogue Sentences',
            },
        ),
        migrations.CreateModel(
            name='dialogues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(default=b'', max_length=80)),
                ('condition', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Dialogue',
                'verbose_name_plural': 'Dialogues',
            },
        ),
        migrations.CreateModel(
            name='equipment_positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Equipment's Position",
                'verbose_name_plural': "Equipment's Positions",
            },
        ),
        migrations.CreateModel(
            name='equipment_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Equipment's Type",
                'verbose_name_plural': "Equipment's Types",
            },
        ),
        migrations.CreateModel(
            name='equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('max_stack', models.PositiveIntegerField(blank=True, default=1)),
                ('unique', models.BooleanField(default=False)),
                ('can_remove', models.BooleanField(default=True)),
                ('can_discard', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('attack', models.IntegerField(blank=True, default=0)),
                ('defence', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='event_attacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('mob', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField()),
                ('odds', models.FloatField(blank=True, default=0)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Event Mob',
                'verbose_name_plural': 'Event Mobs',
            },
        ),
        migrations.CreateModel(
            name='event_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(max_length=255)),
                ('trigger_obj', models.CharField(db_index=True, max_length=255)),
                ('condition', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='event_dialogues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('dialogue', models.CharField(max_length=255)),
                ('npc', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Event Dialogues',
                'verbose_name_plural': 'Event Dialogues',
            },
        ),
        migrations.CreateModel(
            name='event_trigger_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('system_data', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Event Trigger Type',
                'verbose_name_plural': 'Event Trigger Types',
            },
        ),
        migrations.CreateModel(
            name='event_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('system_data', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Event's Type",
                'verbose_name_plural': "Event's Types",
            },
        ),
        migrations.CreateModel(
            name='exit_locks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('unlock_condition', models.TextField(blank=True)),
                ('unlock_verb', models.CharField(blank=True, max_length=80)),
                ('locked_desc', models.TextField(blank=True)),
                ('auto_unlock', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Exit Lock',
                'verbose_name_plural': 'Exit Locks',
            },
        ),
        migrations.CreateModel(
            name='foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('max_stack', models.PositiveIntegerField(blank=True, default=1)),
                ('unique', models.BooleanField(default=False)),
                ('can_remove', models.BooleanField(default=True)),
                ('can_discard', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('hp', models.IntegerField(blank=True, default=0)),
                ('mp', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.CreateModel(
            name='game_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(blank=True, max_length=80)),
                ('connection_screen', models.TextField(blank=True)),
                ('solo_mode', models.BooleanField(default=False)),
                ('global_cd', models.FloatField(blank=True, default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('auto_cast_skill_cd', models.FloatField(blank=True, default=1.5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('player_reborn_cd', models.FloatField(blank=True, default=10.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('npc_reborn_cd', models.FloatField(blank=True, default=10.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('can_give_up_quests', models.BooleanField(default=True)),
                ('single_dialogue_sentence', models.BooleanField(default=True)),
                ('auto_resume_dialogues', models.BooleanField(default=True)),
                ('default_home_key', models.CharField(blank=True, max_length=255)),
                ('start_location_key', models.CharField(blank=True, max_length=255)),
                ('default_player_home_key', models.CharField(blank=True, max_length=255)),
                ('default_player_character_key', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Game Setting',
                'verbose_name_plural': 'Game Settings',
            },
        ),
        migrations.CreateModel(
            name='icon_resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('resource', models.ImageField(blank=True, height_field=b'image_height', null=True, upload_to=b'resource/icon', width_field=b'image_width')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Icon Resource',
                'verbose_name_plural': 'Icon Resources',
            },
        ),
        migrations.CreateModel(
            name='image_resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('resource', models.ImageField(blank=True, height_field=b'image_height', null=True, upload_to=b'resource/image', width_field=b'image_width')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Image Resource',
                'verbose_name_plural': 'Image Resources',
            },
        ),
        migrations.CreateModel(
            name='localized_strings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_data', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('origin', models.TextField()),
                ('local', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Localized String',
                'verbose_name_plural': 'Localized Strings',
            },
        ),
        migrations.CreateModel(
            name='npc_dialogues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc', models.CharField(db_index=True, max_length=255)),
                ('dialogue', models.CharField(db_index=True, max_length=255)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'NPC Dialogue',
                'verbose_name_plural': 'NPC Dialogues',
            },
        ),
        migrations.CreateModel(
            name='npc_shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc', models.CharField(db_index=True, max_length=255)),
                ('shop', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'NPC Shop',
                'verbose_name_plural': 'NPC Shops',
            },
        ),
        migrations.CreateModel(
            name='object_creators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('loot_verb', models.CharField(blank=True, max_length=80)),
                ('loot_condition', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Object Creator',
                'verbose_name_plural': 'Object Creators',
            },
        ),
        migrations.CreateModel(
            name='quest_dependencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(db_index=True, max_length=255)),
                ('dependency', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Quest Dependency',
                'verbose_name_plural': 'Quest Dependency',
            },
        ),
        migrations.CreateModel(
            name='quest_dependency_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('system_data', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Quest dependency's Type",
                'verbose_name_plural': "Quest dependency's Types",
            },
        ),
        migrations.CreateModel(
            name='quest_objective_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('system_data', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Quest Objective's Type",
                'verbose_name_plural': "Quest Objective's Types",
            },
        ),
        migrations.CreateModel(
            name='quest_objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(db_index=True, max_length=255)),
                ('ordinal', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(max_length=255)),
                ('object', models.CharField(blank=True, max_length=255)),
                ('number', models.IntegerField(blank=True, default=0)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Quest Objective',
                'verbose_name_plural': 'Quest Objectives',
            },
        ),
        migrations.CreateModel(
            name='quest_reward_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=255)),
                ('object', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(blank=True, default=0)),
                ('odds', models.FloatField(blank=True, default=0)),
                ('quest', models.CharField(blank=True, max_length=255)),
                ('condition', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': "Quest's reward List",
                'verbose_name_plural': "Quest's reward Lists",
            },
        ),
        migrations.CreateModel(
            name='quests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('condition', models.TextField(blank=True)),
                ('action', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
            },
        ),
        migrations.CreateModel(
            name='shop_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('shop', models.CharField(db_index=True, max_length=255)),
                ('goods', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(blank=True, default=1)),
                ('price', models.PositiveIntegerField(blank=True, default=1)),
                ('unit', models.CharField(max_length=255)),
                ('condition', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Shop Object',
                'verbose_name_plural': 'Shop Objects',
            },
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('verb', models.CharField(blank=True, max_length=80)),
                ('condition', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='skill_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('max_stack', models.PositiveIntegerField(blank=True, default=1)),
                ('unique', models.BooleanField(default=False)),
                ('can_remove', models.BooleanField(default=True)),
                ('can_discard', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('skill', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Skill Book',
                'verbose_name_plural': 'Skill Books',
            },
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('cd', models.FloatField(blank=True, default=0)),
                ('passive', models.BooleanField(default=False)),
                ('function', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='two_way_exits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('reverse_name', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Two Way Exit',
                'verbose_name_plural': 'Two Way Exits',
            },
        ),
        migrations.CreateModel(
            name='typeclasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('system_data', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('path', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('can_loot', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Typeclass',
                'verbose_name_plural': 'Typeclasses',
            },
        ),
        migrations.CreateModel(
            name='world_exits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('verb', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('condition', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Exit',
                'verbose_name_plural': 'Exits',
            },
        ),
        migrations.CreateModel(
            name='world_npcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('level', models.PositiveIntegerField(blank=True, default=1)),
                ('condition', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'World NPC',
                'verbose_name_plural': 'World NPCs',
            },
        ),
        migrations.CreateModel(
            name='world_objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('condition', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'World Object',
                'verbose_name_plural': 'World Objects',
            },
        ),
        migrations.CreateModel(
            name='world_rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, unique=True)),
                ('typeclass', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=80)),
                ('background', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.AlterUniqueTogether(
            name='quest_reward_list',
            unique_together=set([('provider', 'object')]),
        ),
        migrations.AlterUniqueTogether(
            name='quest_objectives',
            unique_together=set([('quest', 'ordinal')]),
        ),
        migrations.AlterUniqueTogether(
            name='npc_shops',
            unique_together=set([('npc', 'shop')]),
        ),
        migrations.AlterUniqueTogether(
            name='default_skills',
            unique_together=set([('character', 'skill')]),
        ),
        migrations.AlterUniqueTogether(
            name='default_objects',
            unique_together=set([('character', 'object')]),
        ),
        migrations.AlterUniqueTogether(
            name='creator_loot_list',
            unique_together=set([('provider', 'object')]),
        ),
        migrations.AlterUniqueTogether(
            name='character_models',
            unique_together=set([('key', 'level')]),
        ),
        migrations.AlterUniqueTogether(
            name='character_loot_list',
            unique_together=set([('provider', 'object')]),
        ),
        migrations.AlterUniqueTogether(
            name='career_equipments',
            unique_together=set([('career', 'equipment')]),
        ),
    ]
