# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-15 10:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlddata', '0002_auto_20170423_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client_settings',
        ),
        migrations.AddField(
            model_name='game_settings',
            name='can_close_dialogue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game_settings',
            name='map_room_size',
            field=models.FloatField(blank=True, default=40.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='game_settings',
            name='map_scale',
            field=models.FloatField(blank=True, default=75.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
