# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-28 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlddata', '0003_auto_20170615_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_settings',
            name='npc_reborn_cd',
        ),
        migrations.RemoveField(
            model_name='game_settings',
            name='player_reborn_cd',
        ),
        migrations.AddField(
            model_name='common_characters',
            name='reborn_time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='world_npcs',
            name='reborn_time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='world_rooms',
            name='peaceful',
            field=models.BooleanField(default=False),
        ),
    ]
