# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeclasses', '0005_auto_20160625_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultCharacter',
        ),
        migrations.DeleteModel(
            name='DefaultExit',
        ),
        migrations.DeleteModel(
            name='DefaultGuest',
        ),
        migrations.DeleteModel(
            name='DefaultObject',
        ),
        migrations.DeleteModel(
            name='DefaultPlayer',
        ),
        migrations.DeleteModel(
            name='DefaultRoom',
        ),
        migrations.DeleteModel(
            name='DefaultScript',
        ),
        migrations.DeleteModel(
            name='DoNothing',
        ),
        migrations.DeleteModel(
            name='ScriptBase',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
