# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='honours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.IntegerField(unique=True)),
                ('honour', models.IntegerField(blank=True, db_index=True, default=-1)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Honour',
                'verbose_name_plural': 'Honours',
            },
        ),
    ]
